### ISSUE TITLE
Can local namespace support multi space or regex?

### ISSUE THREAD

**Issue by Hyphen1001** [wendrowycz/go-imports-tidy#12]
Hi, i have a suggestion for this plugin:
![image](https://github.com/wendrowycz/go-imports-tidy/assets/54525019/e2f82e9b-afbc-49e5-b36e-5c7527750f1e)
In local name space, i can only set one namespace,  but my company has two code repo, which started with code.byted.org and git.byed.org, and my company ask us to format imports with 3-part: 
     stdlib
     extrenal lib(such as github.com/\*)
     internal lib(such as code.byted.org/\*, git.byed.org/\*). 

here is a example:
![image](https://github.com/wendrowycz/go-imports-tidy/assets/54525019/6dc0ceb6-2acf-4df0-a74c-5b574a6a3a95)

so this plugin cannot actually help me to format my imports.

i'll appreciate it if i could config both namespace to the local namespace. it can be seperated by comma, or use regex match:
1. seperated by comma: code.byted.org, git.byted.org
2. regex match： ^(code|git).byted.org

thx.

**Comment by wendrowycz** [comment]
I added support for multiple local namespaces, just specify them with a comma. This has been added to [v.1.1.0](https://github.com/wendrowycz/go-imports-tidy/releases/tag/v.1.1.0). It is queued for approval by JB
