### ISSUE TITLE
com.intellij.diagnostic.PluginException

### ISSUE THREAD

**Issue by lougxing** [wendrowycz/go-imports-tidy#19]
Hi， I have a problem， please help me.

version：
Goland 2024.2.3

Question：

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.mokkapps.codesnapintellijextension.actions.OpenInCodeSnapAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.mokkapps.codesnapintellijextension]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by wendrowycz** [comment]
Thank you for bringing this issue to my attention. I am aware of the warning that the function ActionUpdateThread.OLD_EDT is deprecated and will be removed soon. This indicates that the plugin is using a deprecated function, and I want to inform you that this will be addressed in the next version of the plugin.

I will ensure that the necessary changes are made, including overriding the getActionUpdateThread() method to correctly handle the transition to either EDT or BGT as recommended.

Thank you for your understanding, and the fix will be included in the next release.

**Comment by wendrowycz** [comment]
The fix has been implemented in the latest version, which will soon be published on the JetBrains Marketplace. You can also download the new version here: [v1.1.5](https://github.com/wendrowycz/go-imports-tidy/releases/tag/v1.1.5).

**Comment by lougxing** [comment]
3ks for your help.
